spring.application.name=github-action-demo
server.port=${PORT:8080}

# Actuator endpoints for health check and logs
management.endpoints.web.exposure.include=health,logfile
management.endpoint.health.show-details=always
logging.file.name=logs/app.log

# Deployed app URLs and language for health healer
app.health.url=https://github-action-demo-latest.onrender.com/health
app.logs.url=https://github-action-demo-latest.onrender.com/actuator/logfile
app.language=Java
